import json, os
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
from handlers.drawing_game import canvas_get, canvas_append, canvas_meta, canvas_change_word

HTML=r'''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>PiBot Lienzo</title><style>
*{box-sizing:border-box}body{margin:0;background:#0c0c0f;color:#fff;font-family:system-ui,-apple-system,sans-serif}.app{max-width:980px;margin:auto;padding:12px}.head{text-align:center;margin:4px 0 10px}.secret{font-size:22px;font-weight:800;text-align:center;padding:10px;color:#ffd85a}.tools{display:flex;gap:8px;flex-wrap:wrap;align-items:center;justify-content:center;background:#17171d;padding:10px;border-radius:14px;margin-bottom:10px}.palette{display:flex;gap:7px;flex-wrap:wrap;justify-content:center}.sw{width:38px;height:38px;border-radius:50%;border:3px solid #777;padding:0}.sw.sel{border-color:#fff;box-shadow:0 0 0 2px #8c52ff}.tool{min-height:44px;border:0;border-radius:10px;background:#2a2a34;color:white;padding:9px 13px;font-weight:700;font-size:15px}.tool.on{background:#8c52ff}.range{width:150px}.board{width:100%;aspect-ratio:3/2;background:#fff;border-radius:14px;overflow:hidden;border:2px solid #333}.board canvas{display:block;width:100%;height:100%;touch-action:none}.status{text-align:center;color:#bbb;padding:8px;font-size:14px}.viewer .tools,.viewer .secret{display:none}.viewer .head:after{content:' · Lienzo en vivo'}@media(max-width:520px){.app{padding:8px}.head{font-size:21px}.secret{font-size:19px}.tools{gap:6px;padding:8px}.sw{width:34px;height:34px}.tool{font-size:14px;padding:8px 10px}.range{width:115px}.board{aspect-ratio:4/5}}
</style></head><body><div class="app" id="app"><h2 class="head">🎨 PiBot · Dibuja y Adivina</h2><div id="secret" class="secret">Cargando palabra…</div><div class="tools" id="tools"><div class="palette" id="palette"></div><label>Grosor <input class="range" id="w" type="range" min="2" max="34" value="7"></label><button class="tool" id="eraser">🧽 Borrador</button><button class="tool" id="undo">↶ Deshacer</button><button class="tool" id="redo">↷ Rehacer</button><button class="tool" id="clear">🗑 Limpiar</button><button class="tool" id="change">🔄 Cambiar palabra · 100</button></div><div class="board"><canvas id="cv" width="900" height="900"></canvas></div><div class="status" id="status">Dibuja con el dedo, mouse o stylus.</div></div><script>
const q=new URLSearchParams(location.search),game=q.get('game')||'',token=q.get('token')||'',view=q.get('view')==='1';const app=document.getElementById('app'),cv=document.getElementById('cv'),ctx=cv.getContext('2d'),status=document.getElementById('status');if(view)app.classList.add('viewer');
const colors=['#111111','#ffffff','#e53935','#ff8f00','#fdd835','#43a047','#00acc1','#1e88e5','#5e35b1','#d81b60','#795548'];let color=colors[0],eraser=false,down=false,last=null,hist=[],redoS=[],pending=[];
function mkPalette(){const p=document.getElementById('palette');colors.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className='sw'+(i===0?' sel':'');b.style.background=c;b.setAttribute('aria-label','Color '+c);b.addEventListener('click',()=>{color=c;eraser=false;document.getElementById('eraser').classList.remove('on');p.querySelectorAll('.sw').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')});p.appendChild(b)})}mkPalette();
function pos(e){const r=cv.getBoundingClientRect();return[(e.clientX-r.left)*cv.width/r.width,(e.clientY-r.top)*cv.height/r.height]}function stroke(s){ctx.strokeStyle=s.c;ctx.lineWidth=s.w;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(...s.a);ctx.lineTo(...s.b);ctx.stroke()}function start(e){if(view)return;down=true;last=pos(e);hist.push([]);redoS=[];try{cv.setPointerCapture(e.pointerId)}catch(_){ }e.preventDefault()}function move(e){if(!down||view)return;const p=pos(e),s={t:'s',a:last,b:p,c:eraser?'#ffffff':color,w:eraser?30:+document.getElementById('w').value};stroke(s);hist[hist.length-1].push(s);pending.push(s);last=p;e.preventDefault()}function end(e){down=false;try{cv.releasePointerCapture(e.pointerId)}catch(_){ }}cv.addEventListener('pointerdown',start);cv.addEventListener('pointermove',move);cv.addEventListener('pointerup',end);cv.addEventListener('pointercancel',end);
function redraw(){ctx.clearRect(0,0,cv.width,cv.height);for(const g of hist)for(const s of g)stroke(s)}document.getElementById('eraser').onclick=()=>{eraser=!eraser;document.getElementById('eraser').classList.toggle('on',eraser)};document.getElementById('undo').onclick=()=>{if(hist.length){redoS.push(hist.pop());redraw();pending=[{t:'clear'},...hist.flat()]}};document.getElementById('redo').onclick=()=>{if(redoS.length){hist.push(redoS.pop());redraw();pending=[{t:'clear'},...hist.flat()]}};document.getElementById('clear').onclick=()=>{hist=[];redoS=[];ctx.clearRect(0,0,cv.width,cv.height);pending=[{t:'clear'}]};
async function meta(){if(view)return;try{const r=await fetch('/api/meta?game='+encodeURIComponent(game)+'&token='+encodeURIComponent(token),{cache:'no-store'}),d=await r.json();document.getElementById('secret').textContent=d.word?'🤫 Tu palabra: '+d.word.toUpperCase():'⚠️ Esta ronda ya terminó';}catch(_){document.getElementById('secret').textContent='⚠️ No pude cargar la palabra'}}meta();document.getElementById('change').onclick=async()=>{if(view)return;status.textContent='Cambiando palabra…';try{const r=await fetch('/api/change?game='+encodeURIComponent(game)+'&token='+encodeURIComponent(token),{method:'POST'}),d=await r.json();if(d.word){document.getElementById('secret').textContent='🤫 Tu palabra: '+d.word.toUpperCase();document.getElementById('clear').click();status.textContent='Palabra cambiada · 100 PiPesos';}else status.textContent=d.error==='money'?'No tienes 100 PiPesos':'No pude cambiar la palabra';}catch(_){status.textContent='No pude cambiar la palabra'}};
setInterval(async()=>{if(view){try{const r=await fetch('/api/draw?game='+encodeURIComponent(game)+'&token='+encodeURIComponent(token),{cache:'no-store'});if(r.ok){const a=await r.json();ctx.clearRect(0,0,cv.width,cv.height);for(const s of a){if(s.t==='clear')ctx.clearRect(0,0,cv.width,cv.height);else if(s.t==='s')stroke(s)}}}catch(_){}return}if(!pending.length)return;const b=pending.splice(0);try{const r=await fetch('/api/draw?game='+encodeURIComponent(game)+'&token='+encodeURIComponent(token),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});if(!r.ok)pending.unshift(...b)}catch(_){pending.unshift(...b)}},160);
</script></body></html>'''
class H(BaseHTTPRequestHandler):
 def _send(self,code,body,ctype='application/json'):
  b=body.encode();self.send_response(code);self.send_header('content-type',ctype);self.send_header('content-length',len(b));self.send_header('cache-control','no-store');self.end_headers();self.wfile.write(b)
 def do_GET(self):
  u=urlparse(self.path)
  if u.path=='/draw': return self._send(200,HTML,'text/html; charset=utf-8')
  if u.path=='/health': return self._send(200,'{"ok":true}')
  if u.path=='/api/draw':
   q=parse_qs(u.query);d=canvas_get(q.get('game',[''])[0],q.get('token',[''])[0]);return self._send(200 if d is not None else 403,json.dumps(d if d is not None else {'error':'forbidden'}))
  if u.path=='/api/meta':
   q=parse_qs(u.query);d=canvas_meta(q.get('game',[''])[0],q.get('token',[''])[0]);return self._send(200 if d is not None else 403,json.dumps(d if d is not None else {'error':'forbidden'}))
  self._send(404,'{"error":"not found"}')
 def do_POST(self):
  u=urlparse(self.path);q=parse_qs(u.query)
  if u.path=='/api/change':
   d=canvas_change_word(q.get('game',[''])[0],q.get('token',[''])[0]);return self._send(200 if d is not None else 403,json.dumps(d if d is not None else {'error':'forbidden'}))
  if u.path!='/api/draw':return self._send(404,'{}')
  try:data=json.loads(self.rfile.read(min(int(self.headers.get('content-length','0')),200000)))
  except:return self._send(400,'{}')
  ok=canvas_append(q.get('game',[''])[0],q.get('token',[''])[0],data);self._send(200 if ok else 403,'{"ok":'+('true' if ok else 'false')+'}')
 def log_message(self,*a):pass
def run_server():
 port=int(os.getenv('PORT','8080')); ThreadingHTTPServer(('',port),H).serve_forever()
